### ISSUE TITLE
E5108 attempt to index a nil value 

### ISSUE THREAD

**Issue by bitterjug** [karb94/neoscroll.nvim#39]
Following up [this comment](https://github.com/karb94/neoscroll.nvim/issues/31#issuecomment-879485991).
I just installed neoscroll, using Vim Plug, and all the bindings give this message.

`E5108: Error executing lua ...onfig/nvim/plugged/neoscroll.nvim/lua/neoscroll/init.lua:306: attempt to index a nil value`

Line 306 of init.ula is:
```lua
    if data.win_lines_above_cursor <= vim[so_scope].scrolloff then
```

I include the whole of that file at the end of this issue.

This is my whole `init.vim`, no other plugins are loaded.

```vim
if empty(glob('~/.config/nvim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall | source $MYVIMRC
endif

call plug#begin()
  Plug 'karb94/neoscroll.nvim'
call plug#end()
lua require('neoscroll').setup()
```

And this is what vim says when I ask it what version it has:

```
:version                                                                                                                                                                       
NVIM v0.5.0-dev+1357-g192f89ea1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissin
g-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNV
IM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/nvim/parts/nvim/build/build/config -I/build/nvim/parts/nvim/build/src -I/build/nvim/parts/nvim/build/.deps/usr/include -I/usr/include -
I/build/nvim/parts/nvim/build/build/src/nvim/auto -I/build/nvim/parts/nvim/build/build/include
Compiled by root@lgw01-amd64-021

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by karb94** [comment]
I deleted the copy paste of my code cause it's irrelevant. I trust you when you say you're up to date :). Now the problem is that I cannot reproduce the issue using your minimal `init.vim`. As I said the line 306 has nothing special in it but just to be completely sure add a print statement just before line 306 like this:
```lua
print(so_scope)
print(vim[so_scope].scrolloff)
```
Then report back the values. If you don't see any print statements when you try to scroll is that somehow you are not using the file you think you're using.

**Comment by RaafatTurki** [comment]
I've got the same with packer
```E5108: Error executing lua .../pack/packer/start/neoscroll.nvim/lua/neoscroll/init.lua:245: attempt to index a nil value```

here are [my configs](https://github.com/RaafatTurki/neovim-me)

**Comment by karb94** [comment]
@RaafatTurki could you come up with a minimal init.vim to reproduce the issue?

**Comment by RaafatTurki** [comment]
@karb94 here are the steps to reproduce:
- install [paq](https://github.com/savq/paq-nvim)
- use this `init.lua`
```lua
require "paq" {
        "karb94/neoscroll.nvim";
}
require('neoscroll').setup()
```
- `:PaqInstall`
- reload neovim
- using `<C-d>` for example and this error appears:
```
E5108: Error executing lua ...te/pack/paqs/start/neoscroll.nvim/lua/neoscroll/init
.lua:245: attempt to index a nil value
```

however I've done all of the above in my main PC and it scrolled just fine, no error.
here are some details for both of my machines:
### PC
```
os: Arch x86_64
kern: 5.13.7-zen1-1-zen
shell: fish
res: 1920x1080 @ 60.00Hz
terminal: alacritty
```
### Laptop (has the issue)
```
os: Arch x86_64
kern: 5.13.7-arch1-1
shell: fish
res: 1366x768 @ 60.02Hz
terminal: xst (same w/ alacritty)
```

**Comment by jaydorsey** [comment]
I'm seeing this same issue, but only on one machine (both share the same configuration via [here](https://github.com/jaydorsey/dotfiles), which is complex, but it's literally the exact error down to the line number posted above)

Laptop with no issues

```
os: Catalina
intel
shell: zsh
terminal: iterm

# will add nvim --version output later this week
```

Laptop with the issue
```
os: macOS 11.4 (big sur)
m1 processor
shell: zsh
terminal: iterm

NVIM v0.5.0-dev+1321-gc57a85d53
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Library/Developer/CommandLineTools/usr/bin/cc -I/opt/homebrew/opt/openssl@1.1/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/jemalloc/include -I/opt/homebrew/opt/gmp/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/jay/repos/neovim/build/config -I/Users/jay/repos/neovim/src -I/Users/jay/repos/neovim/.deps/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/usr/include -I/opt/homebrew/opt/gettext/include -I/Users/jay/repos/neovim/build/src/nvim/auto -I/Users/jay/repos/neovim/build/include
Compiled by jay@macbook.fios-router.home

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/Users/jay/repos/neovim/build/share/nvim"

Run :checkhealth for more info
```

I'm using tmux with both laptops

**Comment by jaydorsey** [comment]
I fixed this, temporarily, by setting `scrolloff = 0` as an option in the `config.lua` file and replacing all instances of `vim[so_scope].scrolloff` with `opts.scrolloff`

Would submit this as a PR but I don't know if this is the best way to do this. Maybe if I was using an `init.lua` instead of a `.vimrc` this wouldn't be an issue because my scrolloff would be readable? I don't have the time to test switching over to an init.lua right now but may loop back on it later.

**Comment by karb94** [comment]
@jaydorsey that is really good insight thanks. It does feel related to the Neovim bug. Could you do a quick test for me in both the machine where Neoscroll works and the one where it doesn't work?

Open neovim and post here the output of these two commands:
```Lua
:lua print(vim.go.scrolloff)
:lua print(vim.wo.scrolloff)
```

Also, could you double check the value of the `so_scope` variable in Neoscroll when you use Neovim? I think this information will tell us the root of the problem.

`vim.wo.scrolloff` should give a random variable (Neovim bug) unless you've set `scrolloff` locally (`setlocal scrolloff=#`, `lua vim.wo.scrolloff=#`, `lua vim.opt.scrolloff=#`).

Unfortunately your solution only works for people that don't use local `scrolloff`. That's why I created the setting `use_local_scrolloff` so I can make that a solution.

**Comment by jaydorsey** [comment]
> ```lua
> lua print(vim.go.scrolloff)
> ```

In the machine where it doesn't work:

- `:lua print(vim.go.scrolloff)` returns `E5108: Error executing lua [string ":lua"]:1: attempt to index field 'go' (a nil value)`
- `:lua print(vim.wo.scrolloff)` returns `6162661584`

In the machine where it works:
- `:lua print(vim.go.scrolloff)` returns `10`
- `:lua print(vim.wo.scrolloff)` returns `2.7569986497433e+18`

Also, more info about the machine where it works:

```NVIM v0.6.0-dev+51-gbfb04812d
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/readline/include -I/usr/local/opt/jemalloc/include -I/usr/local/opt/gmp/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/jaydorsey/repos/neovim/build/config -I/Users/jaydorsey/repos/neovim/src -I/Users/jaydorsey/repos/neovim/.deps/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/usr/local/opt/gettext/include -I/Users/jaydorsey/repos/neovim/build/src/nvim/auto -I/Users/jaydorsey/repos/neovim/build/include
Compiled by jaydorsey@macbook.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/Users/jaydorsey/repos/neovim/build/share/nvim"

Run :checkhealth for more info```

I noticed the working machine is actually on 0.6.0, so I'm going to upgrade the machine that's not working now and see if that fixes `vim.go.scrolloff`

**Comment by jaydorsey** [comment]
Upgrading neovim on the machine that doesn't work fixed the issue I had

Additionally, the `vim.go.scrolloff` behavior now mirrors the behavior of the functional machine (returns `10`). I'm not sure what happened with my 0.5.0 version (I build from source so it's relatively new) but it looks like a neovim upgrade fixes it for me

**Comment by karb94** [comment]
@jaydorsey maybe you had an early nightly build that had problems with the `go` accessor? I will close this issue for now but if upgrading neovim doesn't solve the problem for any of you let me know and i will reopen.

**Comment by jaydorsey** [comment]
Upgrading neovim fixed the issue for me.

I've build straight off the main branch, but not super often and I think the version that didn't work was pretty old (probably 6 months at least?). I assumed it was an M1 issue, not realizing the working machine had a much newer version.
